### ISSUE TITLE
Ošetření volby zobrazení příliš složité

### ISSUE THREAD

**Issue by xtompok** [XMaceska/DU01#1]
Jde to jen s jedním while cyklem a bez `if`u, zkus to zjednodušit.

**Comment by XMaceska** [comment]
#  z = Výběr zobrazení, neplatný vstup ošetřen pomocí vnořené funkce While

while True:
    z = input("Na výběr z několika válcových tečných zobrazení: \n\nL pro Lambertovo zobrazení \nA pro Marinovo zobrazení \nB pro Braunovo zobrazení \nM pro Mercatorovo zobrazení\n\nZvolte požadované zobrazení: ")
    if z == "L" or z == "A" or z == "B" or z == "M":
        break
    else:
       print(f"pro znak \"{z}\" není definováno žádné zobrazení\n")
